using System;
using OwinFramework.Pages.Core.Interfaces;
using OwinFramework.Pages.Core.Interfaces.Builder;

namespace OwinFramework.Pages.Core.BaseClasses
{
    /// <summary>
    /// Base implementation of IComponent. Inheriting from this olass will insulate you
    /// from any future additions to the IComponent interface
    /// </summary>
    public class Component : IComponent
    {
        /// <summary>
        /// The name of this component
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The package that this component is part of. This defines the namespace of
        /// assets generated by this component
        /// </summary>
        public IPackage Package { get; set; }
    }
}
