using System;
using OwinFramework.Pages.Core.Interfaces;
using OwinFramework.Pages.Core.Interfaces.Builder;

namespace OwinFramework.Pages.Core.BaseClasses
{
    /// <summary>
    /// Base implementation of ILayout. Inheriting from this olass will insulate you
    /// from any future additions to the ILayout interface
    /// </summary>
    public class Layout : ILayout
    {
        /// <summary>
        /// The name of this layout
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The package that this layout is part of. This defines the namespace of
        /// assets generated by this layout
        /// </summary>
        public IPackage Package { get; set; }
    }
}
