using System;
using OwinFramework.Pages.Core.Enums;

namespace OwinFramework.Pages.Core.Attributes
{
    /// <summary>
    /// Attach this attribute to an element to specify its deployment mechanism
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    public class DeployedAsAttribute: Attribute
    {
        /// <summary>
        /// Constructs and initializes an attribute that defines how to deploy the
        /// assets that are generated by this element
        /// </summary>
        /// <param name="deployment">The deployment scheme for this element</param>
        public DeployedAsAttribute(AssetDeployment deployment)
        {
            Deployment = deployment;
        }

        /// <summary>
        /// The deployment scheme for this element
        /// </summary>
        public AssetDeployment Deployment { get; set; }
    }
}
